src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->getFirstname()." ".$this->getLastname();
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank()
     * @Assert\Length(max = 100, min = 5)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $body;

    /**
     * @ORM\ManyToOne(targetEntity=Author::class)
     */
    private $author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Post;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'row_attr' => ["class" => "mb-3"],
                'attr' => [
                    "class" => "form-control",
                    "placeholder" => "Indiquer le titre de l'article"
                ],
                'help' => "Le titre ne doit pas avoir plus de <b>100</b> caractères",
                'help_attr' => ["class" => "small"],
                'help_html' => true,
                'label' => 'Titre: '
            ])
            ->add('body', TextareaType::class, [
                'attr' => [
                    "class" => "form-control",
                    "placeholder" => "Contenu de l'article"
                ],
                'help' => "Format HTML autorisé",
                'help_attr' => ["class" => "small"],
                'label' => 'Contenu: '
            ])
            ->add('author', EntityType::class, [
                'label' => 'Auteur: ',
                'attr' => ["class" => "form-select"],
                'row_attr' => ["class" => "mb-3"],
                'placeholder' => "Choisissez un auteur",
                'class' => Author::class,
                'choice_label' => function(Author $author) {
                    return $author->getFullname();
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
            'required' => false
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/post", name="post_")
 */
class PostController extends AbstractController
{
    //@Cache(expires="+2 hours")

    /**
     * @Route("", name="index")
     */
    public function index(Request $request, PostRepository $postRepository): Response
    {
        if( $request->query->has('author') ) {
            $idAuthor = $request->query->getInt('author');
            $posts = $postRepository->findAllFromAuthor($idAuthor);
        } else {
            $posts = $postRepository->findAllWithAuthor();
        }

        // dump($posts);

        $response = $this->render('post/index.html.twig', [
            "posts" => $posts
        ]);

        $expire = new \DateTime();
        $expire->modify("+2 hours");
        $response
            ->setPublic()
            ->setExpires($expire);

        return $response;
    }

    /**
     * @Route("/detail/{id}", name="detail")
     */
    public function detail(int $id, PostRepository $postRepository): Response
    {
        $post = $postRepository->findWithAuthor($id);

        return $this->render('post/detail.html.twig', [
            "post" => $post
        ]);
    }

    /**
     * @Route("/add", name="add")
     */
    public function add(Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);
        if( $form->isSubmitted() && $form->isValid() ) {
            // $form->getData();
            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash("success", "L'article a bien été enregistré");
            return $this->redirectToRoute('post_index');
        }

        return $this->render('post/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function edit(Post $post, Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);
        if( $form->isSubmitted() && $form->isValid() ) {
            $entityManager->flush();

            $this->addFlash("success", "L'article a bien été enregistré");
            return $this->redirectToRoute('post_edit', ['id' => $post->getId()]);
        }

        return $this->renderForm('post/edit.html.twig', [
            'form' => $form
        ]);
    }

    /**
     * @Route("/save", name="save")
     */
    public function save(Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = (new Post())
            ->setTitle("Article de présentation de doctrine")
            ->setBody("<p>Pour insérer notre entité <b class='text-primary'>Post</b> en base de données, 
nous allons utiliser l'objet <b class='text-primary'>Doctrine Entity Manager</b>.</p>");

        if( $request->query->has("save") ) {
            $entityManager->persist($post); // met l'entité dans la mémoire de doctrine
            $entityManager->flush();        // enregistre l'entité en base

            $this->addFlash("success", "L'article a bien été enregistré");
            return $this->redirectToRoute("post_save");
        }

        return $this->render('post/save.html.twig', [
            'post' => $post
        ]);
    }

}

templates/post/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles{% endblock %}

{% block body %}
    <div class="float-end">
        <a href="{{ path('post_index') }}" class="btn btn-sm btn-outline-secondary">
            Retour à la liste
        </a>
    </div>
    <article>
        <h2>{{ post.title }}</h2>
        <p>
            <small><b>Auteur:</b> {{ post.author.fullname }} ({{ post.author.email }})</small>
        </p>
        <div>
            {{ post.body | raw }}
        </div>
    </article>
{% endblock %}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer des articles{% endblock %}

{% form_theme form _self %}

{%- block form_errors -%}
    {%- if errors|length > 0 -%}
        <div class="text-danger mb-2">
            {%- for error in errors -%}
                <span>{{ error.message }}</span><br />
            {%- endfor -%}
        </div>
    {%- endif -%}
{%- endblock form_errors -%}

{% block body %}
    {{ parent() }}

    <div class="mb-3">
        <a href="{{ path('post_index') }}" class="btn btn-outline-secondary">Retour</a>
    </div>

    {# {{ form(form) }} #}

    {# {{ form_start(form) }}
    {{ form_rest(form) }}
    <div class="mb-3">
        <button class="btn btn-outline-primary">Enregistrer</button>
    </div>
    {{ form_end(form) }} #}

    {{ form_start(form) }}
    {{ form_row(form.title) }}

    <div class="mb-3">
        {{ form_label(form.body) }}
        {{ form_errors(form.body) }}
        <br />
        {{ form_widget(form.body) }}
        {{ form_help(form.body) }}
    </div>

    {{ form_row(form.author) }}

    <div class="mb-3">
        <button class="btn btn-outline-primary">Enregistrer</button>
    </div>
    {{ form_end(form) }}

{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles{% endblock %}

{% block body %}
    {{ parent() }}

    <div class="mb-3">
        <a href="{{ path('post_add') }}" class="btn btn-outline-primary">Ajouter</a>
    </div>

    <p>
        <a href="https://symfony.com/doc/current/reference/forms/types.html" target="_blank">Référence FormType</a>
    </p>

    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Contenu</th>
            <th>Auteur</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.body|striptags|slice(0, 30) ~ "..." }}</td>
                <td>
                    <a href="{{ path('post_index', { 'author': post.author.id }) }}">
                        {{ post.author.fullname }}</a>
                </td>
                <td>
                    <a href="{{ path('post_detail', {"id": post.id}) }}"> Détail</a> |
                    <a href="{{ path('post_edit', {"id": post.id}) }}"> Modifier </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/post/save.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enregistrer un Article{% endblock %}

{% block body %}
    {{ parent() }}

    <h3>Article à enregistrer</h3>

    <div>
        <p>
            <b>Titre: </b> {{ post.title }}
        </p>

        <p>
            <b>Contenu: </b><br />
            {{ post.body|raw }}
        </p>
    </div>

    <div class="mt-3">
        <a href="{{ path('post_save', {"save": "post"}) }}" class="btn btn-outline-primary">
            Enregistrer</a>
    </div>

{% endblock %}